apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx04
  name: nginx04
spec:
  containers:
  - image: nginx
    name: nginx04
    resources:
      requests:
        memory: "100Mi"
        cpu: "0.5"
      limits:
        memory: "200Mi"
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
