apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx06
  name: nginx06
spec:
  volumes:
  - name: secret
    secret:
      secretName: mysecret
      optional: false
  containers:
  - image: nginx
    name: nginx06
    resources: {}
    volumeMounts:
    - name: secret
      mountPath: "/etc/secrets"
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
