apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx02
  name: nginx02
spec:
  volumes:
  - name: config
    configMap:
      name: cfgvolume
  containers:
  - image: nginx
    name: nginx02
    resources: {}
    volumeMounts:
      - name: config
        mountPath: "/etc/cfg"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
