apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx05
  name: nginx05
spec:
  containers:
  - image: nginx
    name: nginx05
    resources: {}
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: user
            optional: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
