apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx03
  name: nginx03
spec:
  containers:
  - image: nginx
    name: nginx03
    resources: {}
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
