apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx01
  name: nginx01
  namespace: ch3p00
spec:
  containers:
  - image: nginx
    name: nginx01
    ports:
    - containerPort: 80
      name: webport
    resources: {}
    readinessProbe:
      initialDelaySeconds: 20
      periodSeconds: 25
      httpGet:
        path: /
        port: webport
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 25
      httpGet:
        path: /
        port: webport
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
