apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: ch2p02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
