apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: justchecking
value: 100
preemptionPolicy: Never
globalDefault: false
description: "This priority class will not cause other pods to be preempted."
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: justchecking
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: mypqrq
spec:
  hard:
    pods: "2"
  scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["justchecking"]
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: justchecking
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: justchecking